<template>
  <div class="guide-page"><section class="page-header"><div><p class="eyebrow">Getting Started</p><h1>使用指南</h1><p>按下面顺序完成第一次研究流程：先看市场，再看资产，最后用组合和模拟账户验证想法。</p></div><el-button type="primary" @click="$router.push('/')">进入市场驾驶舱</el-button></section><el-alert title="本工具提供数据、回测和学习材料，不构成投资建议。行情可能延迟，历史回测不代表未来结果。" type="warning" :closable="false" show-icon class="mb-4"/><section class="step-grid"><article v-for="(step,index) in steps" :key="step.title" class="step-card"><span class="step-index">0{{ index+1 }}</span><div><h2>{{ step.title }}</h2><p>{{ step.description }}</p><el-button text type="primary" @click="$router.push(step.path)">{{ step.action }}<el-icon class="ml"><ArrowRight /></el-icon></el-button></div></article></section><section class="faq-panel"><h2>常见问题与阅读方法</h2><el-collapse><el-collapse-item v-for="item in faqs" :key="item.title" :title="item.title"><p>{{ item.answer }}</p></el-collapse-item></el-collapse></section></div>
</template>
<script setup>
const steps=[{title:'从市场驾驶舱开始',description:'查看指数、宏观资产与热门标的。使用顶部搜索可直接定位 ticker。',action:'打开市场',path:'/'},{title:'阅读资产详情',description:'先核对数据源、更新时间、币种与延迟提示，再查看 K 线、收益和风险指标。',action:'浏览 SPY',path:'/stock/SPY'},{title:'在组合实验室验证想法',description:'输入有效 ticker，设定区间、权重、成本和再平衡规则，重点看回撤与数据覆盖提示。',action:'打开组合',path:'/portfolio'},{title:'用模拟账户练习执行',description:'模拟买卖由后端计算现金、持仓和盈亏。没有融资，余额和持仓不足会被拦截。',action:'打开模拟账户',path:'/simulation'},{title:'每天读一份宏观简报',description:'财经政策页聚合公开权威来源；金融课堂解释概念与可能的市场传导。',action:'查看财经政策',path:'/news'}]
const faqs=[{title:'页面上的数据一定是实时的吗？',answer:'不是。请始终查看页面的数据源、更新时间和延迟提示。免费数据源可能延迟、缺失或临时不可用。'},{title:'回测结果可以当作收益预测吗？',answer:'不能。回测基于历史价格和设定的假设，不能覆盖未来市场环境、滑点或执行风险。'},{title:'如何使用财经政策页？',answer:'先看来源与发布时间，再打开原文核对上下文。平台只做公开标题、摘要和链接的导航，不替代原始发布。'},{title:'应该从哪一节金融课堂开始？',answer:'建议先读 ETF、利率与债券、期货，再把课程里关联的 ticker 打开，结合真实行情练习观察。'}]
</script>
<style lang="scss" scoped>
.guide-page{max-width:1200px;margin:0 auto}.page-header{display:flex;justify-content:space-between;align-items:flex-end;gap:16px;margin-bottom:18px}.eyebrow{color:$color-accent;font-size:12px;font-weight:700}.page-header h1{color:$text-primary;font-size:24px;margin:4px 0 6px}.page-header p,.step-card p,.faq-panel p{color:$text-secondary;line-height:1.65}.step-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.step-card{background:$bg-card;border:1px solid $border-color;border-radius:$radius-lg;padding:18px;display:flex;gap:16px;min-height:170px}.step-index{color:$color-accent;font-weight:700;font-size:22px;font-variant-numeric:tabular-nums}.step-card h2,.faq-panel h2{color:$text-primary;font-size:17px;margin-bottom:7px}.ml{margin-left:4px}.faq-panel{background:$bg-card;border:1px solid $border-color;border-radius:$radius-lg;padding:18px;margin-top:16px}@media(max-width:750px){.step-grid{grid-template-columns:1fr}.page-header{align-items:flex-start;flex-direction:column}}
</style>
